# Generated by carnix 0.10.1: carnix generate-nix
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO;
  wasm_bindgen_cli = crates.crates.wasm_bindgen_cli."0.2.43" deps;
  __all = [ (wasm_bindgen_cli {}) ];
  deps.aho_corasick."0.7.3" = {
    memchr = "2.2.0";
  };
  deps.argon2rs."0.2.5" = {
    blake2_rfc = "0.2.18";
    scoped_threadpool = "0.1.9";
  };
  deps.arrayvec."0.4.10" = {
    nodrop = "0.1.13";
  };
  deps.ascii."0.8.7" = {};
  deps.assert_cmd."0.11.1" = {
    escargot = "0.4.0";
    predicates = "1.0.1";
    predicates_core = "1.0.0";
    predicates_tree = "1.0.0";
  };
  deps.atty."0.2.11" = {
    termion = "1.5.2";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.autocfg."0.1.2" = {};
  deps.backtrace."0.3.15" = {
    cfg_if = "0.1.7";
    rustc_demangle = "0.1.14";
    autocfg = "0.1.2";
    backtrace_sys = "0.1.28";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.backtrace_sys."0.1.28" = {
    libc = "0.2.54";
    cc = "1.0.36";
  };
  deps.base64."0.9.3" = {
    byteorder = "1.3.1";
    safemem = "0.3.0";
  };
  deps.bitflags."1.0.5" = {};
  deps.blake2_rfc."0.2.18" = {
    arrayvec = "0.4.10";
    constant_time_eq = "0.1.3";
  };
  deps.buf_redux."0.8.1" = {
    memchr = "2.2.0";
    safemem = "0.2.0";
  };
  deps.byteorder."1.3.1" = {};
  deps.cc."1.0.36" = {};
  deps.cfg_if."0.1.7" = {};
  deps.chrono."0.4.6" = {
    num_integer = "0.1.39";
    num_traits = "0.2.6";
    time = "0.1.42";
  };
  deps.chunked_transfer."0.3.1" = {};
  deps.cloudabi."0.0.3" = {
    bitflags = "1.0.5";
  };
  deps.constant_time_eq."0.1.3" = {};
  deps.crossbeam_deque."0.2.0" = {
    crossbeam_epoch = "0.3.1";
    crossbeam_utils = "0.2.2";
  };
  deps.crossbeam_epoch."0.3.1" = {
    arrayvec = "0.4.10";
    cfg_if = "0.1.7";
    crossbeam_utils = "0.2.2";
    lazy_static = "1.3.0";
    memoffset = "0.2.1";
    nodrop = "0.1.13";
    scopeguard = "0.3.3";
  };
  deps.crossbeam_utils."0.2.2" = {
    cfg_if = "0.1.7";
  };
  deps.curl."0.4.21" = {
    curl_sys = "0.4.18";
    libc = "0.2.54";
    socket2 = "0.3.8";
    openssl_probe = "0.1.2";
    openssl_sys = "0.9.44";
    kernel32_sys = "0.2.2";
    schannel = "0.1.15";
    winapi = "0.2.8";
  };
  deps.curl_sys."0.4.18" = {
    libc = "0.2.54";
    libz_sys = "1.0.25";
    cc = "1.0.36";
    pkg_config = "0.3.14";
    openssl_sys = "0.9.44";
    winapi = "0.3.7";
  };
  deps.difference."2.0.0" = {};
  deps.dirs."1.0.5" = {
    redox_users = "0.3.0";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.docopt."1.1.0" = {
    lazy_static = "1.3.0";
    regex = "1.1.6";
    serde = "1.0.90";
    strsim = "0.9.1";
  };
  deps.either."1.5.2" = {};
  deps.env_logger."0.6.1" = {
    atty = "0.2.11";
    humantime = "1.2.0";
    log = "0.4.6";
    regex = "1.1.6";
    termcolor = "1.0.4";
  };
  deps.escargot."0.4.0" = {
    lazy_static = "1.3.0";
    log = "0.4.6";
    serde = "1.0.90";
    serde_json = "1.0.39";
  };
  deps.failure."0.1.5" = {
    backtrace = "0.3.15";
    failure_derive = "0.1.5";
  };
  deps.failure_derive."0.1.5" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
    synstructure = "0.10.1";
  };
  deps.filetime."0.2.5" = {
    cfg_if = "0.1.7";
    redox_syscall = "0.1.54";
    libc = "0.2.54";
  };
  deps.float_cmp."0.4.0" = {
    num_traits = "0.2.6";
  };
  deps.foreign_types."0.3.2" = {
    foreign_types_shared = "0.1.1";
  };
  deps.foreign_types_shared."0.1.1" = {};
  deps.fuchsia_cprng."0.1.1" = {};
  deps.hashbrown."0.1.8" = {
    byteorder = "1.3.1";
    scopeguard = "0.3.3";
  };
  deps.heck."0.3.1" = {
    unicode_segmentation = "1.2.1";
  };
  deps.httparse."1.3.3" = {};
  deps.humantime."1.2.0" = {
    quick_error = "1.2.2";
  };
  deps.id_arena."2.2.1" = {
    rayon = "1.0.3";
  };
  deps.idna."0.1.5" = {
    matches = "0.1.8";
    unicode_bidi = "0.3.4";
    unicode_normalization = "0.1.8";
  };
  deps.itertools."0.7.11" = {
    either = "1.5.2";
  };
  deps.itoa."0.4.4" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."1.3.0" = {};
  deps.leb128."0.2.3" = {};
  deps.libc."0.2.54" = {};
  deps.libz_sys."1.0.25" = {
    libc = "0.2.54";
    cc = "1.0.36";
    pkg_config = "0.3.14";
  };
  deps.log."0.3.9" = {
    log = "0.4.6";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.7";
  };
  deps.matches."0.1.8" = {};
  deps.matrixmultiply."0.1.15" = {
    rawpointer = "0.1.0";
  };
  deps.memchr."2.2.0" = {};
  deps.memoffset."0.2.1" = {};
  deps.mime."0.2.6" = {
    log = "0.3.9";
  };
  deps.mime_guess."1.8.7" = {
    mime = "0.2.6";
    phf = "0.7.24";
    unicase = "1.4.2";
    phf_codegen = "0.7.24";
  };
  deps.multipart."0.15.4" = {
    buf_redux = "0.8.1";
    httparse = "1.3.3";
    log = "0.4.6";
    mime = "0.2.6";
    mime_guess = "1.8.7";
    quick_error = "1.2.2";
    rand = "0.4.6";
    safemem = "0.3.0";
    tempdir = "0.3.7";
    twoway = "0.1.8";
  };
  deps.ndarray."0.12.1" = {
    itertools = "0.7.11";
    matrixmultiply = "0.1.15";
    num_complex = "0.2.1";
    num_traits = "0.2.6";
  };
  deps.nodrop."0.1.13" = {};
  deps.normalize_line_endings."0.2.2" = {};
  deps.num_complex."0.2.1" = {
    num_traits = "0.2.6";
  };
  deps.num_integer."0.1.39" = {
    num_traits = "0.2.6";
  };
  deps.num_traits."0.2.6" = {};
  deps.num_cpus."1.10.0" = {
    libc = "0.2.54";
  };
  deps.numtoa."0.1.0" = {};
  deps.openssl."0.10.21" = {
    bitflags = "1.0.5";
    cfg_if = "0.1.7";
    foreign_types = "0.3.2";
    lazy_static = "1.3.0";
    libc = "0.2.54";
    openssl_sys = "0.9.44";
  };
  deps.openssl_probe."0.1.2" = {};
  deps.openssl_src."111.2.1+1.1.1b" = {
    cc = "1.0.36";
  };
  deps.openssl_sys."0.9.44" = {
    libc = "0.2.54";
    cc = "1.0.36";
    openssl_src = "111.2.1+1.1.1b";
    pkg_config = "0.3.14";
    rustc_version = "0.2.3";
  };
  deps.percent_encoding."1.0.1" = {};
  deps.phf."0.7.24" = {
    phf_shared = "0.7.24";
  };
  deps.phf_codegen."0.7.24" = {
    phf_generator = "0.7.24";
    phf_shared = "0.7.24";
  };
  deps.phf_generator."0.7.24" = {
    phf_shared = "0.7.24";
    rand = "0.6.5";
  };
  deps.phf_shared."0.7.24" = {
    siphasher = "0.2.3";
    unicase = "1.4.2";
  };
  deps.pkg_config."0.3.14" = {};
  deps.predicates."1.0.1" = {
    difference = "2.0.0";
    float_cmp = "0.4.0";
    normalize_line_endings = "0.2.2";
    predicates_core = "1.0.0";
    regex = "1.1.6";
  };
  deps.predicates_core."1.0.0" = {};
  deps.predicates_tree."1.0.0" = {
    predicates_core = "1.0.0";
    treeline = "0.1.0";
  };
  deps.proc_macro2."0.4.29" = {
    unicode_xid = "0.1.0";
  };
  deps.quick_error."1.2.2" = {};
  deps.quote."0.6.12" = {
    proc_macro2 = "0.4.29";
  };
  deps.rand."0.4.6" = {
    rand_core = "0.3.1";
    rdrand = "0.4.0";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand."0.5.6" = {
    rand_core = "0.3.1";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.4";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.2";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.2";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.4" = {
    rand_core = "0.4.0";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.2";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rawpointer."0.1.0" = {};
  deps.rayon."1.0.3" = {
    crossbeam_deque = "0.2.0";
    either = "1.5.2";
    rayon_core = "1.4.1";
  };
  deps.rayon_core."1.4.1" = {
    crossbeam_deque = "0.2.0";
    lazy_static = "1.3.0";
    libc = "0.2.54";
    num_cpus = "1.10.0";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.54" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.54";
  };
  deps.redox_users."0.3.0" = {
    argon2rs = "0.2.5";
    failure = "0.1.5";
    rand_os = "0.1.3";
    redox_syscall = "0.1.54";
  };
  deps.regex."1.1.6" = {
    aho_corasick = "0.7.3";
    memchr = "2.2.0";
    regex_syntax = "0.6.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.6.6" = {
    ucd_util = "0.1.3";
  };
  deps.remove_dir_all."0.5.1" = {
    winapi = "0.3.7";
  };
  deps.rouille."3.0.0" = {
    base64 = "0.9.3";
    chrono = "0.4.6";
    filetime = "0.2.5";
    multipart = "0.15.4";
    num_cpus = "1.10.0";
    rand = "0.5.6";
    serde = "1.0.90";
    serde_derive = "1.0.90";
    serde_json = "1.0.39";
    sha1 = "0.6.0";
    term = "0.5.2";
    threadpool = "1.7.1";
    time = "0.1.42";
    tiny_http = "0.6.2";
    url = "1.7.2";
  };
  deps.rustc_demangle."0.1.14" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.ryu."0.2.8" = {};
  deps.safemem."0.2.0" = {};
  deps.safemem."0.3.0" = {};
  deps.schannel."0.1.15" = {
    lazy_static = "1.3.0";
    winapi = "0.3.7";
  };
  deps.scoped_threadpool."0.1.9" = {};
  deps.scopeguard."0.3.3" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.90" = {
    serde_derive = "1.0.90";
  };
  deps.serde_derive."1.0.90" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
  };
  deps.serde_json."1.0.39" = {
    itoa = "0.4.4";
    ryu = "0.2.8";
    serde = "1.0.90";
  };
  deps.sha1."0.6.0" = {};
  deps.siphasher."0.2.3" = {};
  deps.smallvec."0.6.9" = {};
  deps.socket2."0.3.8" = {
    cfg_if = "0.1.7";
    libc = "0.2.54";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.strsim."0.9.1" = {
    hashbrown = "0.1.8";
    ndarray = "0.12.1";
  };
  deps.syn."0.15.33" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    unicode_xid = "0.1.0";
  };
  deps.synstructure."0.10.1" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
    unicode_xid = "0.1.0";
  };
  deps.tempdir."0.3.7" = {
    rand = "0.4.6";
    remove_dir_all = "0.5.1";
  };
  deps.tempfile."3.0.7" = {
    cfg_if = "0.1.7";
    rand = "0.6.5";
    remove_dir_all = "0.5.1";
    redox_syscall = "0.1.54";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.term."0.5.2" = {
    byteorder = "1.3.1";
    dirs = "1.0.5";
    winapi = "0.3.7";
  };
  deps.termcolor."1.0.4" = {
    wincolor = "1.0.1";
  };
  deps.termion."1.5.2" = {
    numtoa = "0.1.0";
    libc = "0.2.54";
    redox_syscall = "0.1.54";
    redox_termios = "0.1.1";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.threadpool."1.7.1" = {
    num_cpus = "1.10.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.54";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.tiny_http."0.6.2" = {
    ascii = "0.8.7";
    chrono = "0.4.6";
    chunked_transfer = "0.3.1";
    log = "0.4.6";
    url = "1.7.2";
  };
  deps.treeline."0.1.0" = {};
  deps.twoway."0.1.8" = {
    memchr = "2.2.0";
  };
  deps.ucd_util."0.1.3" = {};
  deps.unicase."1.4.2" = {
    version_check = "0.1.5";
  };
  deps.unicode_bidi."0.3.4" = {
    matches = "0.1.8";
  };
  deps.unicode_normalization."0.1.8" = {
    smallvec = "0.6.9";
  };
  deps.unicode_segmentation."1.2.1" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.url."1.7.2" = {
    idna = "0.1.5";
    matches = "0.1.8";
    percent_encoding = "1.0.1";
  };
  deps.utf8_ranges."1.0.2" = {};
  deps.vcpkg."0.2.6" = {};
  deps.version_check."0.1.5" = {};
  deps.walrus."0.5.0" = {
    failure = "0.1.5";
    id_arena = "2.2.1";
    leb128 = "0.2.3";
    log = "0.4.6";
    rayon = "1.0.3";
    walrus_macro = "0.5.0";
    wasmparser = "0.29.2";
  };
  deps.walrus_macro."0.5.0" = {
    heck = "0.3.1";
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
  };
  deps.wasm_bindgen_anyref_xform."0.2.43" = {
    failure = "0.1.5";
    walrus = "0.5.0";
  };
  deps.wasm_bindgen_cli."0.2.43" = {
    curl = "0.4.21";
    docopt = "1.1.0";
    env_logger = "0.6.1";
    failure = "0.1.5";
    log = "0.4.6";
    openssl = "0.10.21";
    rouille = "3.0.0";
    serde = "1.0.90";
    serde_derive = "1.0.90";
    serde_json = "1.0.39";
    walrus = "0.5.0";
    wasm_bindgen_cli_support = "0.2.43";
    wasm_bindgen_shared = "0.2.43";
  };
  deps.wasm_bindgen_cli_support."0.2.43" = {
    base64 = "0.9.3";
    failure = "0.1.5";
    log = "0.4.6";
    rustc_demangle = "0.1.14";
    serde_json = "1.0.39";
    tempfile = "3.0.7";
    walrus = "0.5.0";
    wasm_bindgen_anyref_xform = "0.2.43";
    wasm_bindgen_shared = "0.2.43";
    wasm_bindgen_threads_xform = "0.2.43";
    wasm_bindgen_wasm_interpreter = "0.2.43";
  };
  deps.wasm_bindgen_shared."0.2.43" = {};
  deps.wasm_bindgen_threads_xform."0.2.43" = {
    failure = "0.1.5";
    walrus = "0.5.0";
  };
  deps.wasm_bindgen_wasm_interpreter."0.2.43" = {
    failure = "0.1.5";
    log = "0.4.6";
    walrus = "0.5.0";
  };
  deps.wasmparser."0.29.2" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_util."0.1.2" = {
    winapi = "0.3.7";
  };
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.wincolor."1.0.1" = {
    winapi = "0.3.7";
    winapi_util = "0.1.2";
  };
}
